#!/bin/sh

# Detects OS we're compiling on and generates build_config.mk,
# which in turn gets read while processing Makefile.

# build_config.mk will set the following variables:
# - PORT_CFLAGS will either set:
#               -DLEVELDB_PLATFORM_POSIX if cstatomic is present
#               -DLEVELDB_PLATFORM_NOATOMIC if it is not
# - PLATFORM_CFLAGS with compiler flags for the platform
# - PLATFORM_LDFLAGS with linker flags for the platform

# Delete existing build_config.mk
rm -f build_config.mk

# Detect OS
case `uname -s` in
    Darwin)
        PLATFORM=OS_MACOSX
        echo "PLATFORM_CFLAGS=-DOS_MACOSX" >> build_config.mk
        echo "PLATFORM_LDFLAGS="  >> build_config.mk
        ;;
    Linux)
        PLATFORM=OS_LINUX
        echo "PLATFORM_CFLAGS=-pthread -DOS_LINUX" >> build_config.mk
        echo "PLATFORM_LDFLAGS=-lpthread"  >> build_config.mk
        ;;
    SunOS)
        PLATFORM=OS_SOLARIS
        echo "PLATFORM_CFLAGS=-D_REENTRANT -DOS_SOLARIS"  >> build_config.mk
        echo "PLATFORM_LDFLAGS=-lpthread -lrt" >> build_config.mk
        ;;
    FreeBSD)
        PLATFORM=OS_FREEBSD
        echo "PLATFORM_CFLAGS=-D_REENTRANT -DOS_FREEBSD"  >> build_config.mk
        echo "PLATFORM_LDFLAGS=-lpthread" >> build_config.mk
        ;;
    *)
        echo "Unknown platform!"
        exit 1
esac

echo "PLATFORM=$PLATFORM" >> build_config.mk

# x86-64
PORT_CFLAGS="-fno-omit-frame-pointer"

# On GCC, use libc's memcmp, not GCC's memcmp
PORT_CFLAGS="$PORT_CFLAGS -fno-builtin-memcmp"

# Test whether Google Perf Tools are installed
# http://code.google.com/p/google-perftools/
g++ $CFLAGS -ltcmalloc -x c++ - -o /dev/null 2>/dev/null  <<EOF
  int main() {}
EOF
if [ "$?" = 0 ]; then
	PORT_CFLAGS="$PORT_CFLAGS -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free"
    echo "GOOGLE_PERFTOOLS=1" >> build_config.mk
else
    echo "GOOGLE_PERFTOOLS=0" >> build_config.mk
fi

# Test whether aslib are installed
g++ $CFLAGS -I$HOME/ulib/include -L$HOME/ulib/lib -lulog -x c++ - -o /dev/null 2>/dev/null  <<EOF
  int main() {}
EOF
if [ "$?" = 0 ]; then
    echo "ULIB=1" >> build_config.mk
else
    echo "ULIB=0" >> build_config.mk
fi

echo "PORT_CFLAGS=$PORT_CFLAGS" >> build_config.mk
